name: bakercalculator
description: An app calculating the times of your (bread) baking steps.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_datetime_picker: ^1.3.5
  font_awesome_flutter: ^8.4.0
  intl: ^0.16.1
  sqflite: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
